/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { SessionManagerListResult, SessionManagerResult } from '@deepseek-ai/dsh-session-manager/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$73657373696f6e4d616e61676572 {
    archive: (sessionId: string) => Promise<RemoteResult<SessionManagerResult>>
    deleteAllArchived: () => Promise<RemoteResult<SessionManagerResult>>
    deleteSession: (sessionId: string) => Promise<RemoteResult<SessionManagerResult>>
    deleteSessions: (ids: string[]) => Promise<RemoteResult<SessionManagerResult>>
    list: () => Promise<RemoteResult<SessionManagerListResult>>
    restore: (sessionId: string) => Promise<RemoteResult<SessionManagerResult>>
    restoreMany: (ids?: string[]) => Promise<RemoteResult<SessionManagerResult>>
  }
  interface TypertRemoteMap {
    'sessionManager/archive': (sessionId: string) => Promise<RemoteResult<SessionManagerResult>>
    'sessionManager/deleteAllArchived': () => Promise<RemoteResult<SessionManagerResult>>
    'sessionManager/deleteSession': (sessionId: string) => Promise<RemoteResult<SessionManagerResult>>
    'sessionManager/deleteSessions': (ids: string[]) => Promise<RemoteResult<SessionManagerResult>>
    'sessionManager/list': () => Promise<RemoteResult<SessionManagerListResult>>
    'sessionManager/restore': (sessionId: string) => Promise<RemoteResult<SessionManagerResult>>
    'sessionManager/restoreMany': (ids?: string[]) => Promise<RemoteResult<SessionManagerResult>>
  }
  interface TypertRemoteNamespaceMap {
    'sessionManager': TypertRemoteNamespace$73657373696f6e4d616e61676572
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
