/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_session_manager_sessionManager_archive_parameter_0$schema = z.string()
const _deepseek_ai_dsh_session_manager_sessionManager_archive_result$schema = z.object({
  'ok': z.boolean(),
  'error': z.string(),
  'removedLog': z.boolean(),
  'note': z.string(),
  'removed': z.number(),
  'restored': z.number(),
  'failures': z.array(z.object({
  'id': z.string(),
  'error': z.string(),
})),
})
const _deepseek_ai_dsh_session_manager_sessionManager_deleteAllArchived_result$schema = z.object({
  'ok': z.boolean(),
  'error': z.string(),
  'removedLog': z.boolean(),
  'note': z.string(),
  'removed': z.number(),
  'restored': z.number(),
  'failures': z.array(z.object({
  'id': z.string(),
  'error': z.string(),
})),
})
const _deepseek_ai_dsh_session_manager_sessionManager_deleteSession_parameter_0$schema = z.string()
const _deepseek_ai_dsh_session_manager_sessionManager_deleteSession_result$schema = z.object({
  'ok': z.boolean(),
  'error': z.string(),
  'removedLog': z.boolean(),
  'note': z.string(),
  'removed': z.number(),
  'restored': z.number(),
  'failures': z.array(z.object({
  'id': z.string(),
  'error': z.string(),
})),
})
const _deepseek_ai_dsh_session_manager_sessionManager_deleteSessions_parameter_0$schema = z.array(z.string())
const _deepseek_ai_dsh_session_manager_sessionManager_deleteSessions_result$schema = z.object({
  'ok': z.boolean(),
  'error': z.string(),
  'removedLog': z.boolean(),
  'note': z.string(),
  'removed': z.number(),
  'restored': z.number(),
  'failures': z.array(z.object({
  'id': z.string(),
  'error': z.string(),
})),
})
const _deepseek_ai_dsh_session_manager_sessionManager_list_result$schema = z.object({
  'items': z.array(z.object({
  'id': z.string(),
  'title': z.string(),
  'createdAt': z.number(),
  'cwd': z.string(),
  'archived': z.boolean(),
  'deleted': z.boolean(),
  'live': z.boolean(),
  'origin': z.union([z.literal("main"), z.literal("subagent")]),
  'parentSession': z.string(),
})),
  'groups': z.array(z.object({
  'key': z.string(),
  'workspaceId': z.string(),
  'title': z.string(),
  'path': z.string(),
  'sessions': z.array(z.object({
  'id': z.string(),
  'title': z.string(),
  'createdAt': z.number(),
  'cwd': z.string(),
  'archived': z.boolean(),
  'deleted': z.boolean(),
  'live': z.boolean(),
  'origin': z.union([z.literal("main"), z.literal("subagent")]),
  'parentSession': z.string(),
})),
})),
  'archivedCount': z.number(),
})
const _deepseek_ai_dsh_session_manager_sessionManager_restore_parameter_0$schema = z.string()
const _deepseek_ai_dsh_session_manager_sessionManager_restore_result$schema = z.object({
  'ok': z.boolean(),
  'error': z.string(),
  'removedLog': z.boolean(),
  'note': z.string(),
  'removed': z.number(),
  'restored': z.number(),
  'failures': z.array(z.object({
  'id': z.string(),
  'error': z.string(),
})),
})
const _deepseek_ai_dsh_session_manager_sessionManager_restoreMany_parameter_0$schema = z.union([z.undefined(), z.array(z.string())])
const _deepseek_ai_dsh_session_manager_sessionManager_restoreMany_result$schema = z.object({
  'ok': z.boolean(),
  'error': z.string(),
  'removedLog': z.boolean(),
  'note': z.string(),
  'removed': z.number(),
  'restored': z.number(),
  'failures': z.array(z.object({
  'id': z.string(),
  'error': z.string(),
})),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-session-manager',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-session-manager#sessionManager/archive',
      service: 'sessionManager',
      namespace: 'sessionManager',
      method: 'archive',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session-manager#sessionManager/archive:sessionId',
            schema: _deepseek_ai_dsh_session_manager_sessionManager_archive_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-session-manager/types#SessionManagerResult',
        schema: _deepseek_ai_dsh_session_manager_sessionManager_archive_result$schema,
      },
      sourceLocation: {"file":"packages/session/session-manager/src/index.ts","line":353,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-session-manager#sessionManager/deleteAllArchived',
      service: 'sessionManager',
      namespace: 'sessionManager',
      method: 'deleteAllArchived',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-session-manager/types#SessionManagerResult',
        schema: _deepseek_ai_dsh_session_manager_sessionManager_deleteAllArchived_result$schema,
      },
      sourceLocation: {"file":"packages/session/session-manager/src/index.ts","line":401,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-session-manager#sessionManager/deleteSession',
      service: 'sessionManager',
      namespace: 'sessionManager',
      method: 'deleteSession',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session-manager#sessionManager/deleteSession:sessionId',
            schema: _deepseek_ai_dsh_session_manager_sessionManager_deleteSession_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-session-manager/types#SessionManagerResult',
        schema: _deepseek_ai_dsh_session_manager_sessionManager_deleteSession_result$schema,
      },
      sourceLocation: {"file":"packages/session/session-manager/src/index.ts","line":365,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-session-manager#sessionManager/deleteSessions',
      service: 'sessionManager',
      namespace: 'sessionManager',
      method: 'deleteSessions',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'ids',
          wire: 'ids',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session-manager#sessionManager/deleteSessions:ids',
            schema: _deepseek_ai_dsh_session_manager_sessionManager_deleteSessions_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-session-manager/types#SessionManagerResult',
        schema: _deepseek_ai_dsh_session_manager_sessionManager_deleteSessions_result$schema,
      },
      sourceLocation: {"file":"packages/session/session-manager/src/index.ts","line":379,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-session-manager#sessionManager/list',
      service: 'sessionManager',
      namespace: 'sessionManager',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-session-manager/types#SessionManagerListResult',
        schema: _deepseek_ai_dsh_session_manager_sessionManager_list_result$schema,
      },
      sourceLocation: {"file":"packages/session/session-manager/src/index.ts","line":251,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-session-manager#sessionManager/restore',
      service: 'sessionManager',
      namespace: 'sessionManager',
      method: 'restore',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session-manager#sessionManager/restore:sessionId',
            schema: _deepseek_ai_dsh_session_manager_sessionManager_restore_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-session-manager/types#SessionManagerResult',
        schema: _deepseek_ai_dsh_session_manager_sessionManager_restore_result$schema,
      },
      sourceLocation: {"file":"packages/session/session-manager/src/index.ts","line":292,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-session-manager#sessionManager/restoreMany',
      service: 'sessionManager',
      namespace: 'sessionManager',
      method: 'restoreMany',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'ids',
          wire: 'ids',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session-manager#sessionManager/restoreMany:ids',
            schema: _deepseek_ai_dsh_session_manager_sessionManager_restoreMany_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-session-manager/types#SessionManagerResult',
        schema: _deepseek_ai_dsh_session_manager_sessionManager_restoreMany_result$schema,
      },
      sourceLocation: {"file":"packages/session/session-manager/src/index.ts","line":316,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "The session-manager service: durable restore/delete + inventory.",
        "summary": "The session-manager service: durable restore/delete + inventory.",
        "tags": [],
        "jsDoc": "/** The session-manager service: durable restore/delete + inventory. */",
        "key": "sessionManager",
        "exportName": "SessionManagerService",
        "members": [
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') async list(): Promise<SessionManagerListResult>",
            "summary": "Workspace-grouped inventory of every session not deleted through this service.",
            "jsDoc": "/** Workspace-grouped inventory of every session not deleted through this service. */"
          },
          {
            "kind": "method",
            "name": "restore",
            "signature": "@Remote('restore') async restore(sessionId: string): Promise<SessionManagerResult>",
            "summary": "Restore one archived session (removes it from the durable archive set).",
            "jsDoc": "/** Restore one archived session (removes it from the durable archive set). */"
          },
          {
            "kind": "method",
            "name": "restoreMany",
            "signature": "@Remote('restoreMany') async restoreMany(ids?: string[]): Promise<SessionManagerResult>",
            "summary": "Restore every currently archived (non-deleted) session.",
            "jsDoc": "/** Restore every currently archived (non-deleted) session. */"
          },
          {
            "kind": "method",
            "name": "archive",
            "signature": "@Remote('archive') async archive(sessionId: string): Promise<SessionManagerResult>",
            "summary": "Archive one session into the registry archive set.",
            "jsDoc": "/** Archive one session into the registry archive set. */"
          },
          {
            "kind": "method",
            "name": "deleteSession",
            "signature": "@Remote('deleteSession') async deleteSession(sessionId: string): Promise<SessionManagerResult>",
            "summary": "Delete one session: un-account, hide, and remove its on-disk log.",
            "jsDoc": "/** Delete one session: un-account, hide, and remove its on-disk log. */"
          },
          {
            "kind": "method",
            "name": "deleteSessions",
            "signature": "@Remote('deleteSessions') async deleteSessions(ids: string[]): Promise<SessionManagerResult>",
            "summary": "Delete the given sessions in one batch.",
            "jsDoc": "/** Delete the given sessions in one batch. */"
          },
          {
            "kind": "method",
            "name": "deleteAllArchived",
            "signature": "@Remote('deleteAllArchived') async deleteAllArchived(): Promise<SessionManagerResult>",
            "summary": "Delete every currently archived (non-deleted) session.",
            "jsDoc": "/** Delete every currently archived (non-deleted) session. */"
          }
        ],
        "types": [
          {
            "name": "SessionManagerFailure",
            "declaration": "export interface SessionManagerFailure {\n    id: string;\n    error: string;\n}"
          },
          {
            "name": "SessionManagerGroup",
            "declaration": "export interface SessionManagerGroup {\n    key: string;\n    workspaceId: string;\n    title: string;\n    path: string;\n    sessions: SessionManagerItem[];\n}"
          },
          {
            "name": "SessionManagerItem",
            "declaration": "export interface SessionManagerItem {\n    id: string;\n    title: string;\n    createdAt: number;\n    cwd: string;\n    archived: boolean;\n    deleted: boolean;\n    live: boolean;\n    origin: 'main' | 'subagent';\n    parentSession: string;\n}"
          },
          {
            "name": "SessionManagerListResult",
            "declaration": "export interface SessionManagerListResult {\n    items: SessionManagerItem[];\n    groups: SessionManagerGroup[];\n    archivedCount: number;\n}"
          },
          {
            "name": "SessionManagerResult",
            "declaration": "export interface SessionManagerResult {\n    ok: boolean;\n    error: string;\n    removedLog: boolean;\n    note: string;\n    removed: number;\n    restored: number;\n    failures: SessionManagerFailure[];\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
